name: ws

environment:
  sdk: ^3.11.1

workspace:
  - packages/*
  - packages/*/example

dev_dependencies:
  melos: ^7.5.0
  very_good_analysis: ^10.2.0

melos:
  sdkPath: .fvm/flutter_sdk
  repository: https://github.com/albinpk/widget_theme
  scripts:
    test: |
      cd packages/widget_theme
      fvm dart test --chain-stack-traces
    test:gen: |
      cd packages/widget_theme
      SOURCE_GEN_TEST_UPDATE_GOLDENS=1 fvm dart test --chain-stack-traces
