builders:
  widget_theme:
    import: "package:widget_theme/widget_theme.dart"
    builder_factories: ["widgetThemeBuilder"]
    build_extensions: { ".dart": ["theme.g.dart"] }
    auto_apply: dependents
    build_to: source
    runs_before: ["freezed|freezed"]
