builders:
  widget_theme:
    import: "package:widget_theme/widget_theme.dart"
    builder_factories: ["widgetThemeBuilder"]
    applies_builders: ["source_gen|combining_builder"]
    build_extensions: { ".dart": ["theme.g.part"] }
    auto_apply: dependents
    build_to: cache
