name: widget_theme
description: >
  Code generation utilities for creating widget-specific theme models from
  Flutter widget properties, enabling scalable and consistent theming.
version: 0.1.0-dev.1
repository: https://github.com/albinpk/widget_theme
issue_tracker: https://github.com/albinpk/widget_theme/issues

environment:
  sdk: ^3.11.1

resolution: workspace

dev_dependencies:
  test: ^1.25.6
