/// Types that support lerp.
const lerpTypes = [
  'ActionIconThemeData',
  'Alignment',
  'AlignmentDirectional',
  'AlignmentGeometry',
  'AnimationStyle',
  'AppBarTheme',
  // 'AppBarThemeData', // nullable not supported
  'BadgeThemeData',
  'Border',
  'BorderDirectional',
  'BorderRadius',
  'BorderRadiusDirectional',
  'BorderRadiusGeometry',
  // 'BorderSide', // nullable not supported
  'BottomAppBarTheme',
  'BottomAppBarThemeData',
  'BottomNavigationBarThemeData',
  'BottomSheetThemeData',
  'BoxBorder',
  'BoxConstraints',
  'BoxDecoration',
  'BoxShadow',
  'ButtonStyle',
  'CardTheme',
  'CardThemeData',
  'CarouselViewThemeData',
  'CheckboxThemeData',
  'ChipThemeData',
  'Color',
  // 'ColorScheme', // nullable not supported
  // 'DataTableThemeData', // nullable not supported
  'DatePickerThemeData',
  'Decoration',
  'DecorationImage',
  'DialogTheme',
  'DialogThemeData',
  'DividerThemeData',
  'DrawerThemeData',
  'DropdownMenuThemeData',
  'EdgeInsets',
  'EdgeInsetsDirectional',
  'EdgeInsetsGeometry',
  'ElevatedButtonThemeData',
  'ExpansionTileThemeData',
  'FilledButtonThemeData',
  'FloatingActionButtonThemeData',
  'FlutterLogoDecoration',
  'FontVariation',
  'FontWeight',
  'FractionalOffset',
  'Gradient',
  'HSLColor',
  'HSVColor',
  'IconButtonThemeData',
  'IconThemeData',
  'LinearBorderEdge',
  'LinearGradient',
  'ListTileThemeData',
  'MaterialBannerThemeData',
  'MenuBarThemeData',
  'MenuButtonThemeData',
  'MenuStyle',
  'MenuThemeData',
  'NavigationBarThemeData',
  'NavigationDrawerThemeData',
  'NavigationRailThemeData',
  'Offset',
  'OutlinedBorder',
  'OutlinedButtonThemeData',
  'PopupMenuThemeData',
  'ProgressIndicatorThemeData',
  'RadialGradient',
  'RadioThemeData',
  'Radius',
  'Rect',
  'RelativeRect',
  'RRect',
  'RSuperellipse',
  'ScrollbarThemeData',
  'SearchBarThemeData',
  'SearchViewThemeData',
  'SegmentedButtonThemeData',
  'Shadow',
  'ShapeBorder',
  'ShapeDecoration',
  'Size',
  // 'SliderThemeData', // nullable not supported
  'SnackBarThemeData',
  'SweepGradient',
  'SwitchThemeData',
  // 'TabBarTheme', // nullable not supported
  // 'TabBarThemeData', // nullable not supported
  'TableBorder',
  'TextButtonThemeData',
  'TextSelectionThemeData',
  'TextStyle',
  'TextTheme',
  // 'ThemeData', // nullable not supported
  'TimePickerThemeData',
  'ToggleButtonsThemeData',
  'TooltipThemeData',
  // 'Typography', // nullable not supported
  // 'VisualDensity', // nullable not supported
];
