name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  widget_theme_annotation: 0.1.0-dev.2

dev_dependencies:
  build_runner: ^2.13.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  widget_theme: 0.1.0-dev.2

flutter:
  uses-material-design: true
