name: Publish widget_theme

on:
  push:
    # branches: main
    tags:
      - "widget_theme-v[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/widget_theme

      - name: Check code format
        run: dart format --set-exit-if-changed .
        working-directory: packages/widget_theme

      - name: Analyze
        run: dart analyze
        working-directory: packages/widget_theme

      - name: Dart test
        run: dart test --coverage=coverage
        working-directory: packages/widget_theme

      - name: Format coverage report
        run: |
          dart run coverage:format_coverage \
            --lcov \
            -i packages/widget_theme/coverage \
            -o packages/widget_theme/coverage/lcov.info \
            --report-on=packages/widget_theme/lib

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: albinpk/widget_theme
          working-directory: packages/widget_theme

      - name: Publish - dry run
        run: dart pub publish --dry-run
        working-directory: packages/widget_theme

  publish:
    needs: test
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      environment: "pub.dev"
      working-directory: packages/widget_theme
